name: "just a test"
on: [push,workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: rm -rf build && mkdir build 
        - run: mkdir -p build/windows/amd64 && make coredns BINARY=build/windows/amd64/coredns.exe SYSTEM="GOOS=windows GOARCH=amd64"  BUILDOPTS=""
        - run: rm -rf release && mkdir release
        - run: git diff
        - run: tar -zcf release/coredns_windows_amd64.tgz -C build/windows/amd64 coredns.exe
        - uses: actions/upload-artifact@v4
          with:
              name: window_artifact
              path: release/coredns_windows_amd64.tgz
