name: "just a test"
on: 
  workflow_dispatch:
jobs:
  job1:
    permissions:
      contents: read
      packages: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: super-linter/super-linter@v5.7.2
          env:
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    